apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gettask-ingress
  labels:
    app.kubernetes.io/name: gettask-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: gettask.devopsinsight.biz
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gettask
            port: 
              number: 80
